# 44 | Pentagon numbers
# https://projecteuler.net/problem=44
# 
# Pentagonal numbers are generated by the formula,
# Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# 
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However,
# their difference, 70 − 22 = 48, is not pentagonal.
# 
# Find the pair of pentagonal numbers, Pj and Pk, for which their
# sum and difference are pentagonal and D = |Pk − Pj| is minimised;
# what is the value of D?

is_pent <- function(nr) {
  n <- (sqrt(24 * nr + 1) + 1) / 6
  if (any(floor(n) == n)) {
    return(T)
  }
  return(F)
}

# TODO: optimise the step below
nr <- 2
while (nr > 0) {
  pent <- nr * (3* nr - 1) / 2
  diff <- pent - (1:(nr - 1) * (3 * 1:(nr - 1) - 1) / 2)
  summ <- pent + (1:(nr - 1) * (3 * 1:(nr - 1) - 1) / 2)
  cands <- unlist(sapply(1:(nr-1), function(i) {
    if (is_pent(diff[i]) & is_pent(summ[i])) {
      return(T)
    }
    return(F)
  }))
  if (any(cands)) {
    idx <- which(cands == 1)[1]
    out <- c(pent, diff[idx], summ[idx])
    break  
  }
  nr <- nr + 1
}

print(nr)
